'use client';

/* Minimal types for the subset of the WebMCP Imperative API used by this
   site (https://developer.chrome.com/docs/ai/webmcp/imperative-api):
   registration with a JSON schema, read-only annotations and teardown via
   AbortSignal. Declared here because the `webmcp-types` package ships types
   only (no JS) and its Document augmentation has no global effect. */
declare global {
  namespace WebMCP {
    interface ToolAnnotations {
      readOnlyHint?: boolean;
      untrustedContentHint?: boolean;
      consequentialHint?: boolean;
    }
    type ToolExecute = (
      input?: Record<string, unknown>,
      options?: { signal?: AbortSignal },
    ) => Promise<unknown>;
    interface ModelContextTool {
      name: string;
      description: string;
      inputSchema?: object;
      execute: ToolExecute;
      annotations?: ToolAnnotations;
    }
    interface ModelContext {
      registerTool(
        tool: ModelContextTool,
        options?: { signal?: AbortSignal },
      ): Promise<void>;
    }
  }
  interface Document {
    readonly modelContext?: WebMCP.ModelContext;
  }
}

import { useEffect } from 'react';
import { buscar, normalizar } from '@/lib/busqueda';
import type { EntradaIndice } from '@/lib/busqueda';
import { FAQ } from '@/lib/faq';
import { NORMAS, NORMA_IDS } from '@/lib/normas';
import type { NormaId } from '@/lib/normas';
import { ALL_LINKS } from '@/lib/nav';
import { CRONOLOGIA } from '@/lib/cronologia';
import { ESTADO_VOTACION } from '@/lib/estado-votacion';

/**
 * Read-only WebMCP tools for this site.
 *
 * Registered only when the browser exposes `document.modelContext` (Chrome
 * with WebMCP enabled) so that an agent with the page open can query the
 * content instead of guessing at the DOM. Without the API this renders
 * nothing: it returns null and never touches the DOM.
 *
 * There is no backend and no keys: every tool reads static files or data
 * already public on the site. The search-driven tools consume the index
 * generated by `postbuild`, so they cannot drift from the published
 * content. Page titles, questions and answers stay in Spanish — that is the
 * site's content — but every tool name, description, parameter and output
 * key is English, so agents get a single language on the tool surface.
 */

const ALLOWED_PATHS = [
  '/',
  '/desahucios-y-alquiler/',
  '/fiscal/',
  '/financiacion/',
  '/estado/',
  '/normas/',
];

const searchSchema = {
  type: 'object',
  properties: {
    query: {
      type: 'string',
      description:
        'What to find: a measure, a figure, a question or a topic covered by this site (Spanish content).',
    },
  },
  required: ['query'],
  additionalProperties: false,
} as const;

const readSchema = {
  type: 'object',
  properties: {
    path: {
      type: 'string',
      description:
        'Page to read: a relative path or a URL of this same site, one of: /, /desahucios-y-alquiler/, /fiscal/, /financiacion/, /estado/, /normas/.',
    },
  },
  required: ['path'],
  additionalProperties: false,
} as const;

const faqsSchema = {
  type: 'object',
  properties: {
    query: {
      type: 'string',
      description:
        'Optional filter: only FAQs whose question and answer contain all of these words. Omit to list the FAQs.',
    },
    limit: {
      type: 'integer',
      minimum: 1,
      maximum: 14,
      description: 'Maximum FAQs to return. Defaults to 8.',
    },
  },
  required: [],
  additionalProperties: false,
} as const;

const normSchema = {
  type: 'object',
  properties: {
    id: {
      type: 'string',
      enum: [...NORMA_IDS],
      description: 'Norm identifier, as listed by list_norms.',
    },
  },
  required: ['id'],
  additionalProperties: false,
} as const;

const timelineSchema = {
  type: 'object',
  properties: {
    query: {
      type: 'string',
      description:
        'Optional filter: only timeline entries containing all of these words. Omit to return the whole timeline.',
    },
    limit: {
      type: 'integer',
      minimum: 1,
      maximum: 11,
      description: 'Maximum entries to return. Defaults to 11.',
    },
  },
  required: [],
  additionalProperties: false,
} as const;

let indexCache: EntradaIndice[] | null = null;

async function loadIndex(signal?: AbortSignal): Promise<EntradaIndice[]> {
  if (indexCache) return indexCache;
  const response = await fetch('/search-index.json', { signal });
  if (!response.ok) throw new Error(`HTTP ${response.status}`);
  indexCache = (await response.json()) as EntradaIndice[];
  return indexCache;
}

/** True when every word (2+ letters) of the query appears in the text. */
function matchesAllWords(text: string, query: string): boolean {
  const words = normalizar(query)
    .split(/\s+/)
    .map((w) => w.replace(/^[^a-z0-9]+|[^a-z0-9]+$/g, ''))
    .filter((w) => w.length >= 2);
  if (words.length === 0) return true;
  const haystack = normalizar(text);
  return words.every((w) => haystack.includes(w));
}

function asNumber(value: unknown, fallback: number, min: number, max: number): number {
  return typeof value === 'number' && Number.isInteger(value)
    ? Math.min(Math.max(value, min), max)
    : fallback;
}

function cite(label: string, article: string): { norm: string; article: string } {
  return { norm: label, article };
}

export default function WebMcpTools() {
  useEffect(() => {
    const context = document.modelContext;
    if (!context) return;
    const controller = new AbortController();
    const register = async () => {
      try {
        await context.registerTool(
          {
            name: 'search_site',
            description:
              'Search the reading guide on Spanish housing decrees RDL 26/2026 and RDL 27/2026 (both repealed on 2026-10-02). Returns matching titles, links, sections and excerpts.',
            inputSchema: searchSchema,
            annotations: { readOnlyHint: true },
            execute: async (
              { query }: Record<string, unknown> = {},
              { signal }: { signal?: AbortSignal } = {},
            ) => {
              const text = typeof query === 'string' ? query : '';
              const results = buscar(await loadIndex(signal), text);
              const origin = window.location.origin;
              return results.map((r) => ({
                title: r.titulo,
                href: `${origin}${r.href}`,
                section: r.seccion,
                excerpt: r.extracto,
              }));
            },
          },
          { signal: controller.signal },
        );
        await context.registerTool(
          {
            name: 'read_page',
            description:
              'Return the main text of one of the six site pages, without navigation or menus. Accepts only the six site paths.',
            inputSchema: readSchema,
            annotations: { readOnlyHint: true },
            execute: async (
              { path }: Record<string, unknown> = {},
              { signal }: { signal?: AbortSignal } = {},
            ) => {
              // Accept relative paths and absolute URLs of this same site,
              // so the href returned by search_site works as-is. Anything
              // else (another origin, unknown path) is rejected: this tool
              // only reads the six site pages.
              const raw = typeof path === 'string' ? path : '';
              let pathname: string;
              try {
                const url = new URL(raw, window.location.origin);
                if (url.origin !== window.location.origin) {
                  throw new Error(`Origin not allowed: ${raw}`);
                }
                pathname = url.pathname;
              } catch (error) {
                if (error instanceof Error && error.message.startsWith('Origin')) throw error;
                throw new Error(`Path not allowed: ${raw}`);
              }
              const normalized = pathname === '/' ? '/' : `${pathname.replace(/\/+$/, '')}/`;
              if (!ALLOWED_PATHS.includes(normalized)) {
                throw new Error(`Path not allowed: ${raw}`);
              }
              const response = await fetch(normalized, { signal });
              if (!response.ok) throw new Error(`HTTP ${response.status}`);
              const html = await response.text();
              const document_ = new DOMParser().parseFromString(html, 'text/html');
              const title =
                document_.querySelector('h1')?.textContent?.trim() ?? normalized;
              const body =
                document_.querySelector('main')?.textContent?.replace(/\s+/g, ' ').trim() ??
                '';
              return { title, text: body.slice(0, 4000) };
            },
          },
          { signal: controller.signal },
        );
        await context.registerTool(
          {
            name: 'list_pages',
            description:
              'List the six site pages with their paths and labels.',
            inputSchema: { type: 'object', properties: {}, additionalProperties: false },
            annotations: { readOnlyHint: true },
            execute: async () => {
              const origin = window.location.origin;
              return ALL_LINKS.map((link) => ({
                path: link.href === '/' ? '/' : `${link.href}/`,
                url: link.href === '/' ? `${origin}/` : `${origin}${link.href}/`,
                label: link.label,
              }));
            },
          },
          { signal: controller.signal },
        );
        await context.registerTool(
          {
            name: 'get_faqs',
            description:
              'Return the frequently asked questions with their full answers and cited norms/articles. Pass query to filter, otherwise the first FAQs are listed.',
            inputSchema: faqsSchema,
            annotations: { readOnlyHint: true },
            execute: async ({ query, limit }: Record<string, unknown> = {}) => {
              const max = asNumber(limit, 8, 1, 14);
              const text = typeof query === 'string' ? query.trim() : '';
              const origin = window.location.origin;
              const pool = text
                ? FAQ.filter((f) =>
                    matchesAllWords(`${f.pregunta} ${f.respuesta.join(' ')}`, text),
                  )
                : FAQ;
              return pool.slice(0, max).map((f) => ({
                id: f.id,
                question: f.pregunta,
                answer: f.respuesta.join('\n\n'),
                citations: f.citas.map((c) => cite(NORMAS[c.norma].etiqueta, c.art)),
                href: `${origin}/#${f.id}`,
              }));
            },
          },
          { signal: controller.signal },
        );
        await context.registerTool(
          {
            name: 'list_norms',
            description:
              'List every cited norm with its label, official title and BOE identifier. Use get_norm for the permalink of one norm.',
            inputSchema: { type: 'object', properties: {}, additionalProperties: false },
            annotations: { readOnlyHint: true },
            execute: async () => {
              const origin = window.location.origin;
              return NORMA_IDS.map((id) => ({
                id,
                label: NORMAS[id].etiqueta,
                title: NORMAS[id].titulo,
                boe: NORMAS[id].boe ?? null,
                href: `${origin}/normas/#${id}`,
              }));
            },
          },
          { signal: controller.signal },
        );
        await context.registerTool(
          {
            name: 'get_norm',
            description:
              'Return the official title, BOE identifier and permalink (BOE/ELI) of one cited norm.',
            inputSchema: normSchema,
            annotations: { readOnlyHint: true },
            execute: async ({ id }: Record<string, unknown> = {}) => {
              const key = typeof id === 'string' ? id : '';
              if (!(key in NORMAS)) {
                throw new Error(`Unknown norm id: ${key || '(empty)'}`);
              }
              const norm = NORMAS[key as NormaId];
              const origin = window.location.origin;
              return {
                id: norm.id,
                label: norm.etiqueta,
                title: norm.titulo,
                boe: norm.boe ?? null,
                eli: norm.eli ?? null,
                href: `${origin}/normas/#${norm.id}`,
              };
            },
          },
          { signal: controller.signal },
        );
        await context.registerTool(
          {
            name: 'get_timeline',
            description:
              'Return the timeline of the two decrees (publication, entry into force, deferred effects, deadlines) with cited norms/articles. Pass query to filter.',
            inputSchema: timelineSchema,
            annotations: { readOnlyHint: true },
            execute: async ({ query, limit }: Record<string, unknown> = {}) => {
              const max = asNumber(limit, 11, 1, 11);
              const text = typeof query === 'string' ? query.trim() : '';
              const pool = text
                ? CRONOLOGIA.filter((e) => matchesAllWords(`${e.fecha} ${e.que}`, text))
                : CRONOLOGIA;
              return pool.slice(0, max).map((e) => ({
                date: e.fecha,
                event: e.que,
                citations: e.citas.map((c) => cite(NORMAS[c.norma].etiqueta, c.art)),
              }));
            },
          },
          { signal: controller.signal },
        );
        await context.registerTool(
          {
            name: 'get_site_status',
            description:
              'Return the parliamentary status of the two decrees (vote date, results, whether anything still applies).',
            inputSchema: { type: 'object', properties: {}, additionalProperties: false },
            annotations: { readOnlyHint: true },
            execute: async () => ({
              status: ESTADO_VOTACION.status,
              voteDate: ESTADO_VOTACION.fechaVotacion,
              lastUpdated: ESTADO_VOTACION.lastUpdated,
              results: ESTADO_VOTACION.resultados,
              note: ESTADO_VOTACION.notaFutura,
            }),
          },
          { signal: controller.signal },
        );
      } catch {
        // Without a real WebMCP (flag off, another browser) there is nothing
        // to do: the page works exactly the same without tools.
      }
    };
    void register();
    return () => controller.abort();
  }, []);

  return null;
}
